# Dockerfile.dev - Development/Debug environment
FROM ruby:3.3.8-alpine3.21 AS builder
LABEL maintainer="Rapid7"

# Development: include development and test groups (exclude only coverage)
ARG BUNDLER_CONFIG_ARGS="set force_ruby_platform 'true' set no-cache 'true' set system 'true' set without 'coverage'"
ARG BUNDLER_FORCE_CLEAN="false"
ENV APP_HOME=/usr/src/metasploit-framework
ENV TOOLS_HOME=/usr/src/tools
ENV BUNDLE_IGNORE_MESSAGES="true"
WORKDIR $APP_HOME

COPY Gemfile* metasploit-framework.gemspec Rakefile $APP_HOME/
COPY lib/metasploit/framework/version.rb $APP_HOME/lib/metasploit/framework/version.rb
COPY lib/metasploit/framework/rails_version_constraint.rb $APP_HOME/lib/metasploit/framework/rails_version_constraint.rb
COPY lib/msf/util/helper.rb $APP_HOME/lib/msf/util/helper.rb

RUN apk add --no-cache \
      autoconf \
      bash \
      bison \
      build-base \
      curl \
      ruby-dev \
      openssl-dev \
      readline-dev \
      sqlite-dev \
      postgresql-dev \
      libffi-dev \
      libpcap-dev \
      libxml2-dev \
      libxslt-dev \
      yaml-dev \
      zlib-dev \
      ncurses-dev \
      git \
      go \
    && echo "gem: --no-document" > /etc/gemrc \
    && gem update --system \
    && bundle config $BUNDLER_CONFIG_ARGS \
    && bundle install --jobs=8 \
    && if [ "${BUNDLER_FORCE_CLEAN}" == "true" ]; then \
         bundle clean --force; \
       fi \
    && rm -rf /usr/local/bundle/cache \
    && chmod -R a+rX /usr/local/bundle

ENV GO111MODULE=off
RUN mkdir -p $TOOLS_HOME/bin && \
    cd $TOOLS_HOME/bin && \
    curl -O https://dl.google.com/go/go1.24.0.src.tar.gz && \
    tar -zxf go1.24.0.src.tar.gz && \
    rm go1.24.0.src.tar.gz && \
    cd go/src && \
    ./make.bash

##########################################################################

FROM ruby:3.3.8-alpine3.21
LABEL maintainer="Rapid7"
ARG TARGETARCH
ARG user_name=developer
ARG user_id
ARG group_id
ARG features_repository="https://github.com/uraitakahito/features.git"
ARG dotfiles_repository="https://github.com/uraitakahito/dotfiles.git"

ENV APP_HOME=/usr/src/metasploit-framework
ENV TOOLS_HOME=/usr/src/tools
ENV NMAP_PRIVILEGED=""
ENV METASPLOIT_GROUP=metasploit

#
# Git
#
RUN apk add --no-cache git

#
# clone features
#
RUN cd /usr/src && \
  git clone --depth 1 ${features_repository}

#
# Add user and install common utils.
#
RUN USERNAME=${user_name} \
    USERUID=${user_id} \
    USERGID=${group_id} \
    CONFIGUREZSHASDEFAULTSHELL=true \
    UPGRADEPACKAGES=false \
      /usr/src/features/src/common-utils/install.sh

RUN addgroup -S $METASPLOIT_GROUP

# Add developer user to metasploit group for gem write access
RUN adduser ${user_name} ${METASPLOIT_GROUP}

RUN apk add --no-cache curl bash sqlite-libs nmap nmap-scripts nmap-nselibs \
    postgresql-libs python3 py3-pip py3-impacket py3-requests ncurses libcap su-exec alpine-sdk \
    openssl-dev nasm nodejs npm
RUN \
    if [ "${TARGETARCH}" = "arm64" ]; \
    then apk add --no-cache gcc musl-dev python3-dev libffi-dev gcompat; \
    else apk add --no-cache mingw-w64-gcc; \
    fi

RUN /usr/sbin/setcap cap_net_raw,cap_net_bind_service=+eip $(which ruby)
RUN /usr/sbin/setcap cap_net_raw,cap_net_bind_service=+eip $(which nmap)

COPY --from=builder /usr/local/bundle /usr/local/bundle
RUN chown -R root:metasploit /usr/local/bundle && \
    chmod -R g+w /usr/local/bundle && \
    find /usr/local/bundle -type d -exec chmod g+s {} \;
COPY . $APP_HOME/
COPY --from=builder $TOOLS_HOME $TOOLS_HOME
RUN chown -R root:metasploit $APP_HOME/ && \
    chmod -R g+w $APP_HOME/ && \
    find $APP_HOME -type d -exec chmod g+s {} \;
RUN gem update --system
RUN cp -f $APP_HOME/docker/database.yml $APP_HOME/config/database.yml

ENV GOPATH=$TOOLS_HOME/go
ENV GOROOT=$TOOLS_HOME/bin/go
ENV PATH=${PATH}:${GOPATH}/bin:${GOROOT}/bin

USER ${user_name}

#
# dotfiles
#
RUN cd /home/${user_name} && \
  git clone --depth 1 ${dotfiles_repository} && \
  dotfiles/install.sh

# Install Claude Code
RUN curl -fsSL https://claude.ai/install.sh | bash

WORKDIR $APP_HOME

ENTRYPOINT ["docker/entrypoint.dev.sh"]

# Default: keep container running for manual msfconsole startup
CMD ["sleep", "infinity"]
